sudo: required
services:
- docker
env:
  global:
  - DOCKER_USERNAME=guillaumejacquenot
  - secure: "Me5SLVZVfYXO5q5w65REGYWYciuP5FT2Wed72+Icdnz2VZk1ZnZuxXffp3lxO8bcS7Fu/Z0GJ0gfE7Jlym4H2NoneVqfX3qtGZ+VpyORM6t8hylaw1yAWt7RVzjC6VsQBozKUqV8UVD4Xn7JeSJruSEsDWRQ+cjrU+sHQMQPj+BK2IrUOuCAZ/1UbqEzts2AUviRn+1SL6TtHvaKwklS70pBah9WuVp1k6khT9j5EXjAi+LQyUZAAs3nkp689vhhVRwSRMaaT2mZwpgC+vrh031oAa8TlT1uUxA2zlUe+Jo3VVJK3b9oCKZ/y8TJcOlRhYWCRjRshqKFUVGYD/IC+edd4Gx4t223ToGNjOsBVNOybKWKUXqVYiypf3V+MbDqL2z8peop/FR5igME1RTlvQ1I1PJ84riSZ2HH0WyOH7MjYesdbIdZhlsgtLtvNKSvXB6T0gS9JDOVl2awBrsOqddaDpsAYLdxcTzub6SOxlJtvAdbPZCeyH9wOW5mmQGx+ZwG3Y5bV+AZqi1Upxxy31hA6ce20egLI+F3YGYZPpwKRWUCOGAAG8Pnorv+MqHU0mdpUHRN5gPa78UucBxE4FIMr29E5TFCmwsfRxe5zpPdJhwwzHElBVsLSKNy1h7SafhHP/DnzCcH34dfTtTBAVP2o6ecz2X57BuUHTclNL4="

before_install:
- echo "Before install"
before_script:
- docker pull sirehna/base-image-centos75-gcc485 || true
script:
- docker build --pull --cache-from sirehna/base-image-centos75-gcc485 --tag sirehna/base-image-centos75-gcc485 .
after_script:
- docker images
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  docker push sirehna/base-image-centos75-gcc485 ;
  fi
notifications:
  email: true
